version: "3.9"

services:
  web:
    build: .
    container_name: weather_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn weather_analytics_api.api:app --reload --host 0.0.0.0 --port 8000

